CREATE TABLE Users(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FULLNAME TEXT NOT NULL,
	EMAIL TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	USERTYPE TEXT NOT NULL
	);


CREATE TABLE Tutor(
	BOROUGH INTEGER NOT NULL,
	SUBJECTS TEXT NOT NULL
	);
