CREATE TABLE Users(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FULLNAME TEXT NOT NULL,
	EMAIL TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	USERTYPE TEXT NOT NULL
	);


CREATE TABLE Tutor(
	ID INTEGER NOT NULL,
	BOROUGH TEXT NOT NULL,
	SUBJECT TEXT NOT NULL,
	PRICE INTEGER NOT NULL,
	DETAILS TEXT NOT NULL
	);

CREATE TABLE Student(
	ID INTEGER NOT NULL,
	BOROUGH TEXT NOT NULL
);

CREATE TABLE Slots (
	ID INTEGER NOT NULL,
	DAY TEXT NOT NULL,
	TIMESLOT TEXT NOT NULL,
	AVAILABILITY TEXT DEFAULT "True"
);


CREATE TABLE Requests (
	STUDENTID INTEGER NOT NULL,
	TUTORID	INTEGER NOT NULL,
	DAY TEXT NOT NULL,
	TIMESLOT TEXT NOT NULL,
	DETAILS TEXT NOT NULL,
	STATUS TEXT DEFAULT "Pending",
  REQUESTID INTEGER PRIMARY KEY AUTOINCREMENT
);
