CREATE TABLE Users(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FULLNAME TEXT NOT NULL,
	EMAIL TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	USERTYPE TEXT NOT NULL
	);


CREATE TABLE Tutor(
	ID INTEGER PRIMARY KEY,
	BOROUGH TEXT NOT NULL,
	SUBJECT TEXT NOT NULL,
	PRICE INTEGER NOT NULL,
	DETAILS TEXT NOT NULL
	);

CREATE TABLE Student(
	ID INTEGER PRIMARY KEY,
	BOROUGH TEXT NOT NULL
);

CREATE TABLE Slots (
	SLOTS TEXT NOT NULL,
	AVAILABILITY TEXT NOT NULL
);
